services:
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - sinapis-app

  sinapis:
    build:
      context: ./daily_god
    restart: unless-stopped
    expose:
      - 8000
    depends_on:
      - memcached
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/mediafiles/
    env_file: ./daily_god/.env.prod
    networks:
      - sinapis-app
      - outside

  frontend-proxy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: sinapis.xyz
    volumes:
      - static_volume:/www/html/staticfiles/
      - media_volume:/www/html/mediafiles/
      - caddy_data:/data
    depends_on:
      - sinapis
    networks:
      - sinapis-app

networks:
  sinapis-app:
    driver: bridge
  outside:
    external: true

volumes:
  static_volume:
  media_volume:
  caddy_data:
