services:
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  mustard-seed:
    build: .
    container_name: django-docker
    depends_on:
      - memcached
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - mustard-seed