services:
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - default

  sinapis:
    build: .
    expose:
      - 8000
    depends_on:
      - memcached
    volumes:
      - static_volume:/home/app/staticfiles/
      - media_volume:/home/app/staticfiles/
    env_file:
      - .env.prod
    networks:
      - default
      - outside

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - static_volume:/home/app/staticfiles/
      - media_volume:/home/app/staticfiles/
    depends_on:
      - sinapis
    networks:
      - default

networks:
  outside:
    external: true

volumes:
  static_volume:
  media_volume:
